### ISSUE TITLE
Feature request: Add timeouts as an arg or env variable

### ISSUE THREAD

**Issue by Lee-Hill** [LUSHDigital/litmus#3]
Currently the timeout is set to 1000ms. Many of our services take longer than this to respond, causing the tests to fail.

It would be good to have a way of setting the timeout using either a variable or an arg

**Comment by LadyDascalie** [comment]
PR #4 implements this feature, just waiting for review

**Comment by ladydascalie** [comment]
Feature added @Lee-Hill
